### ISSUE TITLE
return undefined instead of skipping when transform array?

### ISSUE THREAD

**Issue by naivefun** [jsonata-js/jsonata#418]
```yaml
phone:
  - type: home
    number: 1
  - type: office
```
When transform with `phone.number` it returns `['1']` and skips the 2nd record. Is there a way to enforce the missing fields as `undefined`? like this `['1', undefined]`. The use case is when transform into table columns dynamically, the length/index could mismatch.
